package excecao;

public class Basics {
    
    public static void main(String[] args) {
    
        Aluno a1 = null;
        
        try {
            imprimirNomeDoAluno(a1);
        } catch (Exception excecao) {
            System.out.println("Erro ao imprimir nome de usu√°rio");
        }
    
        /*
        Exception in thread "main" java.lang.NullPointerException
                at excecao.Basics.imprimirNomeDoAluno(Basics.java:16)
                at excecao.Basics.main(Basics.java:20)
        */
        
        try {
            System.out.println(7 / 0);
        } catch (AritmeticException e) {
        //    e.printStackTrace();
            System.out.println("Erro: " + e.getMessage());  // message: / by zero
        }
        
        /*
        Exception in thread "main" java.lang.AritmeticException: / by zero
                at excecao.Basics.main(Basics.java:7)
        */
    }
    
    public static void imprimirNomeDoAluno(Aluno aluno) {
        System.out.println(aluno.nome);
    }
}
